### ISSUE TITLE
i3status external_script

### ISSUE THREAD

**Issue by kontax** [maximbaz/dotfiles#10]
Hey @maximbaz, I love the i3status bar you have and am trying to implement it, however I'm a little confused, think you could help me out?

Within the format of the external_script sections you have for checking package updates, you have:

format = '\?if=line... {line}'
notifications = {...'{output_full}'}}

I can't see either of these options within external_scripts (only {output}) - are you using a different fork or something?

**Comment by maximbaz** [comment]
Hey @kontax, that's right, I use a local version of a couple of PRs that aren't merged yet. I just pushed a commit that adds all of them to a local folder 😉 

https://github.com/maximbaz/dotfiles/commit/ac5fe51039df460ab4278a67cef207b68bc4a274

**Comment by maximbaz** [comment]
Closing, let me know if it helped.

**Comment by kontax** [comment]
Ah brilliant, thanks for the help!
