### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by fwarmuth** [maximbaz/dotfiles#13]
Hey,
i am looking for a jump start for my i3 setup.
your repo looks great! keep it on!
Problem:
I cant figure out which fonts you are using... tried all iconic fonts, but  cant find the correct one.
result:
https://i.imgur.com/awmpqGd.png

any idea?

**Comment by maximbaz** [comment]
hey, the font is in this repo: https://github.com/maximbaz/dotfiles/blob/master/.local/share/fonts/taskbar.ttf

enjoy 😉

**Comment by maximbaz** [comment]
but also do install font awesome, I believe some icons I haven't moved to taskbar font just yet... 

(I move icons to my taskbar.ttf because I need to vertically align some of them)
