### ISSUE TITLE
One more question

### ISSUE THREAD

**Issue by NegativeFeedback** [maximbaz/dotfiles#14]
Can you help me better understand the setup script where it is looking for "Desktop-"? I dont understand what the use case is for this.
Thanks!

**Comment by maximbaz** [comment]
Hey, the idea is that I need slightly different configs on different computers, and to make it simple I decided to make all my computers follow naming conventions, for example all desktop computer hostnames would start from "desktop-", all VM hostnames would start from "vm-", and so forth.

In my particular case I only have two types, "desktop-" and something else, so all I need is "if hostname starts from desktop-, then do that", but you can extend this logic if needed.

Does it make sense?

**Comment by NegativeFeedback** [comment]
Makes sense thanks!
