### ISSUE TITLE
Prompt sometimes get stuck due to gitstatus hack

### ISSUE THREAD

**Issue by maximbaz** [maximbaz/dotfiles#16]
Hey @romkatv, could you help me with something?

This is an issue with my setup (I think), and not with p10k itself, therefore creating a ticket on my end.

I've configured gitstatus via function as you suggested, and I included there the `git status --porcelain` hack in order to detect removed unstaged files.

https://github.com/maximbaz/dotfiles/blob/e122639b3183714a91fae1b4906f5f7d367c47e5/.zsh/prompt.zsh#L129-L132

However what I experience is that once I open a new terminal and navigate to a git repo, my terminal completely hangs, doesn't react to anything I type (except `Ctrl+C`). In a new terminal if I run `htop`, I can see that `git status --porcelain` is being executed all the time, like in an infinite loop. I guess there is some kind of infinite loop happening, but I can't figure out where.

I confirm that if I comment that code block out, the issue goes away.

If I press `Ctrl+C`, I get something like below, but the prompt is still stuck, I can't type anything except `Ctrl+C`.

![image](https://user-images.githubusercontent.com/1177900/66312114-4a7d8780-e910-11e9-9970-f96d37718f2b.png)

If I press `Ctrl+C` many times in a row, I get the prompt back, while branch name is in grey - but as soon as it becomes colorful, my prompt gets stuck again.

Any ideas what could be wrong, or where I should investigate?

**Comment by maximbaz** [comment]
Nevermind, I figured it out 🎉 . Turns out, even if I just add `git status` inside that function, it will result in a visible infinite loop, as if someone is holding `Enter` key.

I fixed this in https://github.com/maximbaz/dotfiles/commit/a5739a0502759106c1822068176198f02ba8c436, if I run `git status` in a subshell it doesn't reproduce 🙊 

Also realized I had to replace `VCS_STATUS_NUM_UNSTAGED` with my own value because it is too generic, but that's minor annoyance.

**Comment by romkatv** [comment]
> Also realized I had to replace `VCS_STATUS_NUM_UNSTAGED` with my own value because it is too generic, but that's minor annoyance.

Interesting. Your code ignores several types of unstaged changes. Is this intended? For example, try this:

```zsh
() {
 emulate -L zsh
 setopt err_return no_unset
 local tmp
 tmp="$(mktemp -d ${TMPDIR:-/tmp}/repo.XXXXXXXXXX)"
 cd $tmp
 git init
 touch a
 git add a
 git commit -m 1
 rm a
 ln -s b a
 git status
}
```

This repository has unstaged files but your prompt will say it's clean.

**Comment by maximbaz** [comment]
This is not intended, but a bug! Thanks for sharing. You've just proven again that your proposal to implement detailed counters in `gitstatus` will be a lot less error-prone and a lot more pleasant to work with than my hacks 😄 So can't wait until this becomes a feature in `gitstatus`!

**Comment by maximbaz** [comment]
Thanks again for the `VCS_STATUS_NUM_UNSTAGED_DELETED` in `gitstatus`, with https://github.com/maximbaz/dotfiles/commit/17144de727efc6d1282e4d707273f81120b7b854 the example above now correctly determines unstaged file 😉
