### ISSUE TITLE
Different scaling factor on external monitor

### ISSUE THREAD

**Issue by calincru** [maximbaz/dotfiles#18]
Hi.  I hope you don't mind that I'm asking this here.  

I have a similar configuration to yours only that currently I have a Full HD laptop. I'm planning to get a 4K one and I was wondering if you ever had to use an external monitor with a smaller (i.e., regular) DPI.  And if that's the case, how did you achieve that with X?

I did some research and I found blogs such as [[1](http://wok.oblomov.eu/tecnologia/mixed-dpi-x11/),[2](https://blog.summercat.com/configuring-mixed-dpi-monitors-with-xrandr.html)] who show how to do it, but it looks pretty hackish and it's not clear to me whether it's achievable without compromising image quality at all.  I've also read that Wayland allows having different scaling factors [[3](https://wiki.archlinux.org/index.php/HiDPI#Multiple_external_monitors)], but some resources claim they achieve it in the same way it can be done with X [[2](https://blog.summercat.com/configuring-mixed-dpi-monitors-with-xrandr.html)].

Any thoughts on this?

**Comment by maximbaz** [comment]
Hey, happy to talk!

In my experience, this is simply impossible to achieve on X, I tried many times and something was always broken, not only image quality, but for example some apps would see the smallest dpi value among all outputs and refuse to occupy the full space of hidpi screen (i.e. they would treat all screens as "normal" dpi), or compositor would behave weirdly, or whatnot.

Wayland on the other hand is completely different story, it supports different DPI values for different screens out of the box, it requires no compositor, and everything is just soooo smooth out of the box. This particular bit (operating several screens, possibly with different DPI values) is much more pleasant (at least in sway).

For the past several years I was periodically trying to switch to Wayland (sway in particular), but something has always been not working well and thus holding me back. This year however I made another attempt, and I am finally satisfied with the current state of affairs, and I remained on sway.

I definitely recommend you to try to move to sway.

After several years of using 4k laptop I am temporarily using a FullHD laptop (also looking into buying a new 4k laptop now btw 🙂), but even with FullHD laptop and two bigger FullHD screens I found myself using slightly different DPI values.

Here's all it takes to do this in sway:

https://github.com/maximbaz/dotfiles/blob/9c4f25f5477ee2d89bbfeeb667463ab766a63113/.config/sway/config#L20-L35

There are many things that are also supported out of the box, for example the following lines listen when I open/close my laptop lid and switch between laptop or external screens:

https://github.com/maximbaz/dotfiles/blob/9c4f25f5477ee2d89bbfeeb667463ab766a63113/.config/sway/config#L37-L38

Let me know if this helps 🙂

**Comment by calincru** [comment]
Thanks for the quick reply.  :smiley:

Haha, now I see your recent commits -- I only checked this repo about 2 weeks ago and now I was about to order the laptop and decided to ask you about this without checking the new files.

Hmm, I guess if Wayland works for you, I should be fine with it too.  I'm a little bit afraid of the little things that are different, such as key press settings, laptop docking, etc.  But since more people are adopting it, even if something goes wrong, they should be dealt with quickly.

Thanks, I'll consider it once I get the new laptop and set it up.  Will let you know how it went.

**Comment by maximbaz** [comment]
Yeah, I can tell you that the progress in Wayland world is clearly visible, every time I tried more and more annoying issues were getting solved 🙂 

Feel free to ask if you get stuck on anything, or just share some cool finding 🙂
