### ISSUE TITLE
ERROR: Failed to install packages to new root

### ISSUE THREAD

**Issue by pbt001** [maximbaz/dotfiles#20]
Hi,

I'm testing your install script and there's a problem after downloading maximbaz.db. This seems to be caused by conflicting packages, i.e.between `virtualbox-host-modules-arch` and `virtual box-host-dkms`. There are 7 other package conflicts before but I'm not sure if that's a problem. Anyways, I get the following output:

```
error: unresolvable package conflicts detected
error: failed rot prepare transaction (conflicting dependencies)
==> ERROR: Failed to install packages to new root
bash: Error on line 168: pacstrap -I /mnt maximbaz
```

How should this be solved and can you suggest a workaround for now to install Arch now?

Thanks!
t1

**Comment by maximbaz** [comment]
Hey, seems like you used an uppercase -i flag to pacstrap instead of lowercase? This worked in my earlier tests, could you please confirm if you get a chance? https://github.com/maximbaz/dotfiles/commit/47cec9613fcedc2c62220a44af813c94480562f4

**Comment by pbt001** [comment]
Oh it should be a lowercase i (just my typo here). The install script does not prompt me to choose the package sources and ends up the errors quoted above.

**Comment by maximbaz** [comment]
I'll close the ticket assuming all the questions have been answered, thanks again for the ping about issues with installation script, and as always feel free to comment here or in a new ticket if you have any other questions, notes or feedback 😉
