### ISSUE TITLE
z4h ssh exception

### ISSUE THREAD

**Issue by n1ete** [maximbaz/dotfiles#22]
thanks to you i switched to z4h, but i couldnt figured out how to connect via ssh without the z4h extensions.....for instance to connect to an router or other more restricted system....can you point me again in the right direction?

thanks again and be well

**Comment by cyrinux** [comment]
Hi @n1ete ,

You need to use zstyle to setup the exclusion:

In your ~/.zshrc add this:

```
zstyle ':z4h:ssh:yourrouter' passthrough yes
zstyle ':z4h:ssh:yourrouter' ssh-command command ssh
```

where `yourrouter` is the shortname you use to access your router. You can setup this in `~/.ssh/config`, for eg:

```
...
Host yourrouter
    Hostname 192.168.42.254
    User root
...
```

Hope this help, regards
