### ISSUE TITLE
[ask] sway windows rounded corners

### ISSUE THREAD

**Issue by AlmightlyGod** [maximbaz/dotfiles#27]
Hello! On the screen I've seen rounded terminal windows corners. Сan you tell how to do the same? I searched a lot, but I still can't find an answer.

**Comment by maximbaz** [comment]
Hey! Apologies for the late reply. I'm not sure what screenshot you are referring to, I don't think I have any rounded corners 🙂 Could you point me to the image?

**Comment by AlmightlyGod** [comment]
Hi again!) I meant a screenshot from README.md in this repository - [https://user-images.githubusercontent.com/1177900/82881781-6f2a7c00-9f40-11ea-936c-78044aeaf52e.png](here it is). As I can see, windows corners slightly (2px or 3px) rounded. Have you used a modified sway or some kind of black magic?

**Comment by maximbaz** [comment]
No magic, sadly 🙂 I think it's just a visual artifact, if I make a zoomed in screenshot, the corners are not rounded:

![image](https://user-images.githubusercontent.com/1177900/97850779-c81eed00-1cf4-11eb-9dd2-395e2835db8e.png)

Might it be that the size of sway gaps gives this effect? If so, here's the setting:

https://github.com/maximbaz/dotfiles/blob/04c8dfa0758d3f1f81c0a34eb14419bea9a5a0b7/.config/sway/config#L21-L23

**Comment by AlmightlyGod** [comment]
Hmm ... maybe. Anyway - thanks for the answer! Your hard work inspired me to try sway again, thanks!

**Comment by maximbaz** [comment]
Happy to hear this 🙂 I am using sway almost a whole year now, and I already know I will not go back to Xorg.

If you get any other issues or comments, do not hesitate to ping me 😉
