### ISSUE TITLE
Cerebro installation?

### ISSUE THREAD

**Issue by cyrinux** [maximbaz/dotfiles#3]
Also, 
I can't install cerebro, do you do something particular for get aur package working?
Build failed for me.
Thanks!

**Comment by maximbaz** [comment]
Hey, unfortunately cerebro is not compiling right now on Arch Linux, here's the tracking ticket for you to subscribe: https://github.com/KELiON/cerebro/issues/426

It's actually me who is maintaining AUR packages for cerebro, you can click on "Enable notifications" on the [AUR page](https://aur.archlinux.org/packages/cerebro) and you'll get an email when cerebro is fixed and can be compiled again.

**Comment by cyrinux** [comment]
Ok great, I will do this,  thanks you ! :)
