### ISSUE TITLE
Issues after using the automated setup

### ISSUE THREAD

**Issue by en1tan** [maximbaz/dotfiles#33]
OS: Garuda Arch i3

Can't update again
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
error: failed retrieving file 'maximbaz-local.db.sig' from disk : Couldn't open file /var/cache/pacman/maximbaz-local/maximbaz-local.db.sig
error: maximbaz-local: missing required signature
error: failed to update maximbaz-local (invalid or corrupted database (PGP signature))
 maximbaz is up to date
error: failed to synchronize all databases
[sudo] password for x1k:
error: maximbaz-local: missing required signature
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
error: failed retrieving file 'maximbaz-local.db.sig' from disk : Couldn't open file /var/cache/pacman/maximbaz-local/maximbaz-local.db.sig
error: maximbaz-local: missing required signature
error: failed to update maximbaz-local (invalid or corrupted database (PGP signature))
 maximbaz is up to date
error: failed to synchronize all databases

![screenshot_20210203-143514](https://user-images.githubusercontent.com/16443589/106754267-11047b80-662d-11eb-98b9-043ad12b4aed.png)

Terminal doesn't look so good

**Comment by maximbaz** [comment]
Hello, you would need to investigate a little more, as of now all I can say is that you are missing a `.sig` file 🙂 

This is the file which you need to sign using `gpg --detach-sign`: `/var/cache/pacman/maximbaz-local/maximbaz-local.db.tar`

**Comment by en1tan** [comment]
`gpg --detach-sign` invalid option

**Comment by maximbaz** [comment]
I have to refer you to `man gpg` and Google to do some research

**Comment by rxmmah** [comment]
what the solution?
i have the same issue
