### ISSUE TITLE
Question: waybar-updates font and alignment

### ISSUE THREAD

**Issue by mordax777** [maximbaz/dotfiles#34]
Firstly, Thank you for your dotfiles. They help me understand sway and set it up for my environment.

I got a quick question regarding the font and aliment of the text of the waybar-updates. Take a look at this:
Yours:
![image](https://user-images.githubusercontent.com/27705384/107068603-1efafd80-67e1-11eb-9f2a-40dff425ea81.png)

Mine:
![image](https://user-images.githubusercontent.com/27705384/107069730-aa28c300-67e2-11eb-89a3-bcdd32d475ba.png)

You can notice that the numbers are much more squashed and put together in my example. I took over your waybar-updates and used some other tooling to get a similar result, but that should not have affected the looks. I checked the style.css from the waybar but also had no luck.

So that why I am writing here, would you know why it is like it is?

`style.css`:
<details><pre>
@define-color background #282828;
@define-color foreground #ebdbb2;
@define-color black      #222222;
@define-color yellow     #fabd2f;
@define-color red        #fb4934;
@define-color green      #b8bb26;

* {
    border: none;
    border-radius: 0;
    font-family: Input, "Font Awesome 5 Free";
    font-size: 13px;
    min-height: 0;
}

window#waybar {
    background: @background;
    color: @foreground;
    transition-property: background-color;
    transition-duration: 0.5s;
}

#workspaces button {
    padding: 0 10px;
    background: transparent;
    color: @foreground;
    border-top: 3px solid @background;
    border-bottom: 3px solid transparent;
}

#workspaces button.focused {
    border-bottom: 3px solid @green;
}

#workspaces button.urgent {
    border-bottom: 3px solid @yellow;
}

#mode {
    background-color: @black;
    border-top: 3px solid @black;
    border-bottom: 3px solid @red;
}

#custom-updates,
#custom-mail,
#custom-vpn.off,
#battery.warning,
#memory.warning,
#cpu.warning,
#custom-dnd.on,
#custom-tablet.on {
    border-bottom: 3px solid @yellow;
}

#custom-systemd,
#battery.critical,
#memory.critical,
#cpu.critical,
#custom-yubikey,
#custom-recording {
    border-bottom: 3px solid @red;
}

#battery.charging {
    border-bottom: 3px solid @green;
}

#mode,
#pulseaudio,
#custom-yubikey,
#custom-systemd,
#custom-updates,
#network,
#cpu,
#memory,
#backlight,
#battery,
#clock {
    padding: 0 6px;
    margin: 0 6px;
}

#custom-vpn,
#custom-dnd,
#custom-tablet,
#custom-recording {
    padding: 0;
    margin: 0 6px;
}

#tray {
    margin-left: -1000000px;
}
</pre></details>

`config`:
<details><pre>
{
    "layer": "top",
    "height": 25,
    "modules-left": [
        "sway/workspaces",
        "sway/mode"
    ],
    "modules-right": [
        "custom/progress",
        "custom/yubikey",
        "custom/systemd",
        "custom/updates",
        "custom/recording",
        "custom/dnd",
        "pulseaudio",
        "network",
        "custom/vpn",
        "cpu",
        "memory",
        "backlight",
        "battery",
        "clock",
        "tray"
    ],

    "custom/progress": {
        "exec": "waybar-progress",
        "return-type": "json",
        "interval": 1
    },
    "custom/yubikey": {
        "exec": "waybar-yubikey",
        "return-type": "json"
    },
    "custom/systemd": {
        "exec": "waybar-systemd",
        "return-type": "json",
        "interval": 10
    },
    "custom/updates": {
        "exec": "waybar-updates show",
        "return-type": "json",
        "signal": 1,
        "on-click-right": "waybar-updates refresh",
        "interval": "once"
    },
    "custom/vpn": {
        "format": "{}",
        "return-type": "json",
        "exec": "waybar-vpn",
        "on-click": "nmcli con up office passwd-file /run/media/aljaz/wrk-stick/work/vpn/office/pass",
        "on-click-right": "nmcli con down office"
    },
    "custom/dnd": {
        "exec": "waybar-dnd",
        "return-type": "json",
        "signal": 2,
        "interval": "once",
        "on-click": "waybar-dnd toggle"
    },
    "custom/recording": {
        "exec": "waybar-recording",
        "return-type": "json",
        "signal": 3,
        "interval": "once"
    },
    "clock": {
        "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
        "format": " {:%a, %d %b    %H:%M}"
    },
    "cpu": {
        "format": " {usage}%",
        "states": {
            "warning": 70,
            "critical": 90
        }
    },
    "memory": {
        "format": " {}%",
        "states": {
            "warning": 70,
            "critical": 90
        }
    },
    "backlight": {
        "format": "{icon} {percent}%",
        "format-icons": [""]
    },
    "battery": {
        "bat": "BAT0",
        "states": {
            "warning": 30,
            "critical": 15
        },
        "format": "{icon} {capacity}%",
        "format-charging": " {capacity}%",
        "format-alt": "{time} {icon}",
        "format-icons": ["", "", "", "", ""]
    },
    "network": {
        "interval": 2,
        "interface": "wlan0",
        "format-wifi": " {essid}",
        "format-ethernet": " {ifname}",
        "format-linked": " {ifname}",
        "format-disconnected": "  ",
        "tooltip-format": "{ifname}: {ipaddr}/{cidr}\n {bandwidthDownBits}\n {bandwidthUpBits}"
    },
    "pulseaudio": {
        "format": "{icon} {volume}%   {format_source}",
        "format-bluetooth": "{icon} {volume}%   {format_source}",
        "format-bluetooth-muted": " {icon}   {format_source}",
        "format-muted": "   {format_source}",
        "format-source": " {volume}%",
        "format-source-muted": "",
        "format-icons": {
            "headphone": "",
            "hands-free": "",
            "headset": "",
            "phone": "",
            "portable": "",
            "car": "",
            "default": ["", "", ""]
        },
        "on-click": "pavucontrol"
    }
}
</pre></details>

`waybar-updates`:
<details><pre>
#!/bin/sh

cache_path="${XDG_CACHE_HOME:-$HOME/.cache}/waybar-updates"

case "$1" in
    show)
        if [ -f "$cache_path" ]; then
            cat "$cache_path"
        else
            printf '{"text": "waybar-updates cache is missing"}\n'
        fi
        ;;
    refresh)
        yay="$(yay -Qu)"
        dif="$(pacdiff -o)"
        reb="$(checkrebuild)"

        yay_n=$(printf "$yay" | grep -c '^')
        dif_n=$(printf "$dif" | grep -c '^')
        reb_n=$(printf "$reb" | grep -c '^')

        text=""
        tooltip=""

        [ -n "$text" -o -n "$reb" ] && text="/${reb_n}${text}"
        [ -n "$reb" ]               && tooltip="Rebuild required:\n\n$reb\n\n${tooltip}"
        [ -n "$text" -o -n "$dif" ] && text="/${dif_n}${text}"
        [ -n "$dif" ]               && tooltip="pacdiff:\n\n$dif\n\n${tooltip}"
        [ -n "$text" -o -n "$yay" ] && text="${yay_n}${text}"
        [ -n "$yay" ]               && tooltip="yay:\n\n$yay\n\n${tooltip}"

        tooltip="$(printf "$tooltip" | perl -pe 's/\n/\\n/g' | perl -pe 's/(?:\\n)+$//')"

        if [ -z "$text" ]; then
            printf '{"text": ""}\n' > "$cache_path"
        else
            printf '{"text": " %s", "tooltip": "%s" }\n' "$text" "$tooltip" > "$cache_path"
        fi

        pkill -RTMIN+1 -x waybar
        ;;
    *)
        echo >&2 "Usage: $0 <show|refresh>"
        exit 1
        ;;
esac
</pre></details>

**Comment by maximbaz** [comment]
Hello 🙂 

Can you tell me if the font is the same in your waybar, ourside of `waybar-updates`? Do you have the same issue in other waybar segments (like CPU%), and do you have the same font in those other segments?

For example I noticed that your `0` doesn't look like my zero, so I am wondering if you specify in your waybar font family `Input`, but in fact you don't have it installed, maybe?

![image](https://user-images.githubusercontent.com/1177900/107071224-b150d080-67e4-11eb-8b3d-6e81d2c2893a.png)

**Comment by maximbaz** [comment]
For reference, here is the link to my specific flavor of Input font that I use:

http://input.fontbureau.com/download/?customize&fontSelection=fourStyleFamily&regular=InputMonoNarrow-Regular&italic=InputMonoNarrow-Italic&bold=InputMonoNarrow-Bold&boldItalic=InputMonoNarrow-BoldItalic&a=0&g=0&i=serifs_round&l=serifs_round&zero=slash&asterisk=height&braces=0&preset=default&line-height=1.1&email=

This is where I put it:

https://github.com/maximbaz/dotfiles/blob/47cd70c97d2cb1a5346a1f25a764af5e3b8c6da1/packages/PKGBUILD#L22-L24

I recommend to grep for `Input` in your dotfiles repo, if you use another font, replace all occurrences with your own font - and then all the apps will respect it 🙂

**Comment by mordax777** [comment]
Ahh yes, I was missing the fonts, thank you! Now my Waybar also looks much better! :slightly_smiling_face: 
![image](https://user-images.githubusercontent.com/27705384/107079379-13630300-67f0-11eb-8d3d-1cb0589b052e.png)

But regarding:
> I recommend to grep for `Input` in your dotfiles repo, if you use another font, replace all occurrences with your own font - and then all the apps will respect it

I noticed that not all my applications respect this font right now and `Input` does not occur in my dotfiles , for example my Terminal. Am I missing some kind of global configuration?
Here my neofetch:
![image](https://user-images.githubusercontent.com/27705384/107079953-e06d3f00-67f0-11eb-9032-482cb3a10973.png)

**Comment by maximbaz** [comment]
Awesome!

Haha I maybe should have said "grep _my_ dotfiles" 😅 

What you are probably missing is this bit, the definition of the global font family `monospace`, this is what many apps will fallback to (especially terminals), unless you override the font in their settings:

https://github.com/maximbaz/dotfiles/blob/47cd70c97d2cb1a5346a1f25a764af5e3b8c6da1/packages/30-font-aliases.conf#L12-L15

**Comment by mordax777** [comment]
Works! Thank you!

Two side questions regarding fonts.

1. Neofetch prints:
`Theme: Adwaita [GTK2], Arc-Gruvbox [GTK3]`
I am wondering if the Adwaita Theme is even required and if not, is it possible to remove it?

2. Does your Kitty terminal take over the Arc-Gruvbox theme? Because in my case I had to

**Comment by maximbaz** [comment]
1. Adwaita is the default theme, I don't think it's possible to remove it, it probably is part of gtk itself 🤔 I'm not 100% sure, there is also something called `adwaita-icon-theme` that provides all the standard icons, but again it's a direct dependency of `gtk` packages, so shouldn't be removed.

Having said that, we don't really need GTK2, this is a good catch. Right now it's being pulled only by `gtk-theme-arc-gruvbox-git`, but we can remove the dependency (@cyrinux will push the update within a few days) and then neofetch will show like so:

![image](https://user-images.githubusercontent.com/1177900/107115409-d4bf5e00-686c-11eb-8c78-f8fdea8fb019.png)

2. No `kitty` does not use `gtk`, therefore it doesn't respect any GTK theme - I set the colors in [kitty.conf](https://github.com/maximbaz/dotfiles/blob/master/.config/kitty/kitty.conf), so that the correct theme is applied regardless of which shell is being used.

**Comment by cyrinux** [comment]
Hi guys, I just remove the gtk2 dep from `gtk-theme-arc-gruvbox-git`.

**Comment by mordax777** [comment]
Hey @cyrinux :wave:
Thanks for being so fast!

I upgraded `gtk-theme-arc-gruvbox-git` to the latest version, but I am still getting both `Adwaita [GTK2] ` and `Arc-Gruvbox [GTK3]` from `neofetch`:
![image](https://user-images.githubusercontent.com/27705384/107130994-27cbfc00-68d3-11eb-8da2-320bf8c2814b.png)

Also, I did not find any change in https://github.com/cyrinux/arc-gruvbox-theme. Could that be the problem, or am I missing something?

@maximbaz A good tip with the `kitty` config, but I have a problem since it seems like kitty is not pulling the config because my terminal looks like this:
![image](https://user-images.githubusercontent.com/27705384/107131068-cc4e3e00-68d3-11eb-9d42-0af16226d00e.png)
I start `kitty` without any extra parameters, and the config does not get pulled, but it works if I specify the path to the config as a parameter while starting with `-c`. Would you know why this is happening?

**Comment by maximbaz** [comment]
[This](https://aur.archlinux.org/cgit/aur.git/commit/?h=gtk-theme-arc-gruvbox-git&id=7162dd1778038c8b9fcf87756a027f407e93f666) was the change, you can delete that dependency manually, and unless you have some other apps that rely on GTK2, delete `gtk2` package as well 🙂 

Hmm no not sure about the config, make sure you don't have a typo and it is located in the place where kitty is looking for it by default: https://sw.kovidgoyal.net/kitty/conf.html

**Comment by mordax777** [comment]
Ah yeah, the linux `spotify` client still uses gtk2 :confused: 

Regarding the kitty configuration, I checked what you said but the path and permissions seem fine.
![image](https://user-images.githubusercontent.com/27705384/107131863-ba23ce00-68da-11eb-9fc3-faaebf63af9c.png)
Tried reinstalling it, did not help

**Comment by mordax777** [comment]
Ah yeah, the linux `spotify` client still uses gtk2 :confused: Do you know if there are any other `spotify` clients? 

Regarding the kitty configuration, I think it has something to do with `fish`. Because when I start a bash shell and then call `kitty` there from the terminal, it pulls the configuration correctly. I did not find any issues to this problem, not sure where I should open a ticket, but it seems more of a problem from `fish`.

**Comment by maximbaz** [comment]
personally I simply open it in the browser 🙂 

hmm interesting, yeah not sure too, never used fish, maybe it has some quirks we are unaware of.

**Comment by mordax777** [comment]
Ill see to get it fixed :slightly_smiling_face: 

Since all my questions regarding font and themes got answered, I am closing this ticket.

Thank you both @maximbaz and @cyrinux for the great support! :smile:
