### ISSUE TITLE
Emoji font

### ISSUE THREAD

**Issue by shvchk** [maximbaz/dotfiles#36]
https://github.com/maximbaz/dotfiles/blob/f907adbb2c60db144b4a956e824aa9996a8017a7/packages/75-joypixels.conf#L46

Not really an issue, just wanted to share that instead of excluding char ranges in fonts one by one you could just exclude it from all fonts (that are not JoyPixels and/or other you want to whitelist 😉) at once:

```xml
    <match target="font">
        <test name="family" compare="not_eq">
            <string>JoyPixels</string>
        </test>
        <edit name="charset" mode="assign" binding="same">
            <minus>
                <name>charset</name>
                <charset>
                    <range>
                        <int>0x1f600</int>
                        <int>0x1f640</int>
                    </range>
                </charset>
            </minus>
        </edit>
    </match>
```

Of course, that's just an example, you could use multiple tests and ranges. Here's what I use: https://gist.github.com/shvchk/b8ba6c7cbf392eb72b1a2e5bff2f131a (long list of emoji ranges from https://www.unicode.org/Public/UCD/latest/ucd/emoji/emoji-data.txt ), plus I blacklist Noto Color Emoji, since browsers seem to ignore these charset edits.

Feel free to close this right away — as I've said, this is not really an issue, just wanted to share : )

**Comment by maximbaz** [comment]
Thank you for sharing, this is very very cool! 

Out of curiosity I started by removing this block altogether and I don't seem to be able to reproduce the issue that led me to try this exclusion in the first place... Do you have a way how to reproduce the issue these days? I'm also thinking, you mentioned that browsers ignore these edits... and I think I only use emojis in browsers (and in electron apps) 🤔 

And another question, do you have a problem where numbers get rendered using emoji font, in some apps or sites or browsers? I don't think it happens often to me these days, but for example while testing I noticed that on [emoji-data.txt](https://www.unicode.org/Public/UCD/latest/ucd/emoji/emoji-data.txt) Firefox does render number with emoji font, while Chromium and Qutebrowsers do not 🙂

**Comment by maximbaz** [comment]
Curiously I concluded that I do not need to exclude any char ranges. Will remove them altogether for now, but if I find a reason to return it, thanks to you I now know a proper way. Thanks again 🙂
