### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by apaaris** [maximbaz/dotfiles#38]
Hi, from the readme I couldn’t understand how to install your configuration... 
I ran the commands from the instructions but something went wrong, it installs something and it changes some options, such as the automatic login in tty, but nothing more
Is there a package list with things we should have pre installed?

**Comment by maximbaz** [comment]
Hello!

This repo is a collection of settings for various apps, I think the best idea would be to look through the repo and if some of these apps you'd like to try, install the app, take my settings as a starting point and adjust them to your liking.

[This file](https://github.com/maximbaz/dotfiles/blob/master/packages/PKGBUILD) contains a list of all the apps that I have installed.

If you want to try my full configuration, with all the apps and all the settings exactly as I use them, you could also try to spin up a VM and install a fresh Arch Linux (maybe using my [install.sh](https://github.com/maximbaz/dotfiles/blob/master/install.sh) directly, but maybe a more educational approach would be if you read that file line by line and learn what is going on there).

And if you have some specific questions, like why a certain thing is done this way and not the other way, I'm happy to elaborate.

Good luck and enjoy the exploration 😉

**Comment by maximbaz** [comment]
Hope that answered the question, see also #39, it has some extra info about the basic setup after the installation.
