### ISSUE TITLE
alexherbo2 repos are gone

### ISSUE THREAD

**Issue by CipherVector** [maximbaz/dotfiles#43]
title is self explanatory.

**Comment by maximbaz** [comment]
Thanks for the ping! The mystery is solved: some of them were moved under [kakoune.cr](https://github.com/alexherbo2/kakoune.cr/tree/master/share/kcr/rc).

I updated `kakoune.cr-git` to package them, and the rest was either removed (if I didnt use them) or copy-pasted directly into the dotfiles repo as part of https://github.com/maximbaz/dotfiles/commit/e5707bb4d57fbc8b930bbb7129f608a77d9a9827
