### ISSUE TITLE
Question: External monitor problem

### ISSUE THREAD

**Issue by mordax7** [maximbaz/dotfiles#46]
Hello @maximbaz,

I have been having issues with my external monitor since the 13th of this moth, and I could not find the problem. However, since I followed your dotfiles a lot while setting up my own, I wondered if you experienced similar issues as I do for a few days. 

The problem is 100% reproducible with my Dell XPS 13 9300 and a HDMI to USB-C adapter:
1. connect the adapter to the laptop
2. boot laptop
3. decrypt partition
4. come to tty

If it works, the display already should detect the signal from the laptop and show the tty login screen. Whatever I try to do, nothing happens and the screen does not get recognized with `swaymsg -t get_outputs`

For a few days, I use this workaround to make it work again:
1. disconnect adapter from the laptop
2. boot laptop
3. decrypt partition
4. come to tty
5. connect adapter

This way, the screen gets the signal, and everything works.

Here are is the `boot journal` from when the adapter is connected(when it does not work):
[broken.txt](https://github.com/maximbaz/dotfiles/files/7877679/broken.txt)

Here is the `boot journal` from when the adapter is disconnected and reconnected once in tty(workaround):
[workaround.txt](https://github.com/maximbaz/dotfiles/files/7877677/workaround.txt)

Here is the `pacman.log` from the night before it broke:
[pacman-2022-01-13.txt](https://github.com/maximbaz/dotfiles/files/7877701/pacman-2022-01-13.txt)

There was also a firmware upgrade for the laptop a few days ago, but I am unsure if that correlates with the issue.

Currently, I am standing a bit in the dark with this. I do not want to bother you with it if you are not familiar with this issue. But can you give me a point in the right direction to continue searching for clues to what could have caused this problem?

**Comment by mordax7** [comment]
Update on the problem:

Today I had the chance to connect a 4k monitor directly to the USB-C port, and it works. So the problem has to be with the HDMI to USB-C adapter. I tried two different adapters, and both had the same problem.

**Comment by maximbaz** [comment]
Hello 👋 To be honest I use external screens very rarely, I've never seen anything like you describe...

**Comment by maximbaz** [comment]
Is it the same monitor, or is it a different monitor? I'd not be very surprised if it's caused by adaptors, but I can't think of anything that you didn't try yet, sorry... 😞

**Comment by mordax7** [comment]
@maximbaz It is bizarre since the workaround also works like this:

1. disconnect adapter(where the monitor is connected to)
2. boot laptop
2. when you come to the decrypting step, plug the adapter back in
3. decrypt
4. monitor should get detected already at `tty`

It could be that the issue came with some firmware update. I noticed some people at work reporting adapter issues(although not with their monitor) for some days now.

Either way, I'll live with the workaround till it miraculously works again.

Thank you for your feedback, and hear you around!

**Comment by maximbaz** [comment]
thanks for sharing, I wish I could have helped more, but at least you have a workaround :)
