### ISSUE TITLE
Can you please share the polybar config files?

### ISSUE THREAD

**Issue by abinlatheef** [maximbaz/dotfiles#47]
I can't find it in here.

**Comment by maximbaz** [comment]
Hi, I don't use polybar 😉 I use waybar

**Comment by abinlatheef** [comment]
Ooh.. sorry my bad😅. Would you mind showing how you implemented that mic thing on the bar? (I assume it shows whether the mic is mute or not). And is there a way I can see it only when the mic is being used?

**Comment by maximbaz** [comment]
This is a standard module of [waybar](https://github.com/maximbaz/dotfiles/blob/a18c92bd1aa923edcab79feac9ea864bb0d31995/.config/waybar/config#L156), it shows pulseaudio / pipewire. It simply shows the volume of input, so if I mute my mic (using shortcut / [my fancy wrapper](https://github.com/maximbaz/dotfiles/blob/master/.local/bin/sway-audio)) then waybar would just show this. Have a look and let me know if you have some further questions 😉

**Comment by abinlatheef** [comment]
Thanks bro💖. This thing is lit.

**Comment by abinlatheef** [comment]
Why did you say `aurutils` is the most reasonable AUR helper out there? Whats wrong with paru?

**Comment by maximbaz** [comment]
nothing is wrong with any of the helpers, aurutils brings you closest to how arch maintainers operate, it allows you using pacman itself for managing aur packages, and let's you learn lots of arch concepts. 

it's totally fine to use paru, don't worry about it 😉

**Comment by abinlatheef** [comment]
I should definitely try it then.
