### ISSUE TITLE
Sorry opening case to get help 

### ISSUE THREAD

**Issue by ciscohack** [maximbaz/dotfiles#48]
Hello Expert,

I want to set up LS_COLOR I tried but the colors not coming correctly. if you don't mind may I have your script to put in my mac and zsh4humans config... would you please share this with me. Thanks 

"/usr/share/LS_COLORS/dircolors.sh"

**Comment by maximbaz** [comment]
Hello, no worries, the script comes from here: 

https://github.com/trapd00r/LS_COLORS

**Comment by ciscohack** [comment]
@maximbaz you are awesome ...  just looked at it.. but this color is everything. Have you modified it to some dir/file-level or using it as it is. if modified please do share your version... i love your customizations

**Comment by maximbaz** [comment]
Not modified anything, I quite like the standard color scheme 🙂 I do use `exa`, so for me the output looks like so - same for you?

![image](https://user-images.githubusercontent.com/1177900/163555036-b47096ba-fe89-44a9-bf0f-ee2e530bfa4b.png)


https://github.com/maximbaz/dotfiles/blob/61a40e111012dd589dad89ff0d31dcd1be8f8529/.zsh-aliases#L12-L15

**Comment by ciscohack** [comment]
@maximbaz yes I also use exa output kind of same... I tried this command dircolors -b LS_COLORS > /usr/share/LS_COLORS/dircolors.sh not working as LS_COLORS folder is not in the path and macOS not allowing to create it... and latest macOS ".local/ " path also have bin path removed. I was trying for xdg-open app. we can manually create folder and put xdg-open file ..will it work ?

**Comment by maximbaz** [comment]
You don't have to use `/usr/share/..`, it's just a convenient place on Linux, drop the file in any other location, even in `$HOME` if you like 😉

**Comment by ciscohack** [comment]
@maximbaz got it. Thanks once again

**Comment by maximbaz** [comment]
Will close but if you get any other question, don't hesitate to ask, here or in a new issue!

**Comment by ciscohack** [comment]
@maximbaz  Thank you so much, my friend.

**Comment by ciscohack** [comment]
@maximbaz My dear friend sorry for bothering you but I think only you help me with this.. is there a better way to connect with you for some basic queries.

Okay as I know you are pro and champion in all sorts of shell scripting and zsh type or prompts. Today while doing some work I found this new prompt style most of the theme style looks awesome and are very clean

https://ohmyposh.dev/docs/themes
 
I know you mostly help powerlvel10k and spaceship team in development and powerlevel10k is very flexible to do so. I tried but was not able to make it. can you help me to make some prompt style?

check the link in that you will find the below-mentioned prompts. is it possible if not then leave it brother thanks

https://ohmyposh.dev/docs/themes

[bubblesextra]
[dracula]
[jandedobbeleer]

**Comment by maximbaz** [comment]
Hey, don't worry this channel is good, also maybe other people will chip in with help 😉 I've not seen that prompt before, so I might be very limited in how much I can really help, I'd suggest explaining in as much details as possible what you tried and what is the issue you are facing, and maybe there's something I might be able to spot? I won't be able to try a new theme myself, unfortunately, lately I didn't have much opportunity to spend time for these fun projects....

**Comment by 1m-N00b** [comment]
Hi @ciscohack 
I saw a post on Reddit with similar content. Also the author, romkatv, [advises](https://www.reddit.com/r/zsh/comments/uhhi3n/comment/i79rl46/?utm_source=share&utm_medium=web2x&context=3)
Sorry if the posters are the same.

---
Forgive me to convey another matter here. @maximbaz 
It seems that `libinput-gestures` is unable to resolve the dependency in the maximbaz repo.
I think the solution is to download `PKGBUILD` from [aur](https://aur.archlinux.org/packages/libinput-gestures) and build it yourself first and `repo-add` it.
```
error: failed to prepare transaction (could not satisfy dependancies)
:: unable to satisfy dependancy dependancy 'libinput-gestures' required by maximbaz
```

**Comment by ciscohack** [comment]
> Hey, don't worry this channel is good, also maybe other people will chip in with help 😉 I've not seen that prompt before, so I might be very limited in how much I can really help, I'd suggest explaining in as much details as possible what you tried and what is the issue you are facing, and maybe there's something I might be able to spot? I won't be able to try a new theme myself, unfortunately, lately I didn't have much opportunity to spend time for these fun projects....

Thanks for the response I just tried classic with rounded but powerlevel10 has huge config set not well versed which section will transform .. anyway I understand your point and no issue thanks a lot once again

**Comment by ciscohack** [comment]
> Hi @ciscohack I saw a post on Reddit with similar content. Also the author, romkatv, [advises](https://www.reddit.com/r/zsh/comments/uhhi3n/comment/i79rl46/?utm_source=share&utm_medium=web2x&context=3) Sorry if the posters are the same.
> 
> Forgive me to convey another matter here. @maximbaz It seems that `libinput-gestures` is unable to resolve the dependency in the maximbaz repo. I think the solution is to download `PKGBUILD` from [aur](https://aur.archlinux.org/packages/libinput-gestures) and build it yourself first and `repo-add` it.
> 
> ```
> error: failed to prepare transaction (could not satisfy dependancies)
> :: unable to satisfy dependancy dependancy 'libinput-gestures' required by maximbaz
> ```

Thanks my friend I will take a look
