### ISSUE TITLE
aurutils update 

### ISSUE THREAD

**Issue by cyrinux** [maximbaz/dotfiles#5]
Hi @maximbaz , 
Do you plan to update i3 check aur scripts? 
Do you allready have something working with aurutils update?
Regards,

**Comment by maximbaz** [comment]
Hey, the scripts are working, but I'm running my fork of aurutils, where I added the support for VCS packages - it is not merged yet, subscribe to https://github.com/AladW/aurutils/pull/283.

**Comment by cyrinux** [comment]
Ok @maximbaz thanks yet
