### ISSUE TITLE
Install script fails

### ISSUE THREAD

**Issue by mortenivar** [maximbaz/dotfiles#50]
Hello Maxim,
Since I had to install a new system, I thought I'd try out your Arch linux installation script at  https://git.io/maximbaz-install.
It didn't work out for me: The first stumbling block was the url, 'https://pkgbuild.com/~maximbaz/repo/'. 
The script looks for the file maximbaz.db and it constructs the path as https://pkgbuild.com/~maximbaz/repo/maximbaz.db' which yields a 404. After changing the url in the script to 'https://pkgbuild.com/~maximbaz/repo/$(uname -m)',  the script continued until line 187,
pacstrap -i /mnt maximbaz-base maximbaz-$(uname -m), where unfortunately it failed.

I could pacstrap /mnt manually, but the script doesn't seem to know where maximbaz-base and maximbaz-$(uname -m) are located.

After that I gave up.

**Comment by maximbaz** [comment]
Thank you for letting me know @mortenivar!

This script is unfortunately very rarely tested, so I appreciate such bug reports!

I think this commit might be the fix,  after which at least the metapackages would be discovered on the correct url:
https://github.com/maximbaz/dotfiles/commit/7fb76f077744af791004c363a24be22571a2823a

I don't have a way to verify that this is the complete fix at the moment, so I'll leave this ticket open as a reminder. If you feel like trying once more - please go ahead, if not - thanks anyway, after you get your Arch installed you are still very welcome to take anything you want from this repo, as well as opening new tickets asking for questions 😉

**Comment by mortenivar** [comment]
You're welcome ;) But this fixes only the first error, I think. The pacstrap error in line 187 is not addressed here?

**Comment by maximbaz** [comment]
Depending on the error... is it failing because it cannot locate the metapackage, or it fails for other reason?

**Comment by mortenivar** [comment]
It must be because it cannot locate the metapackage. The script fails in this line, but I can pacstrap /mnt manually from the command line. That leaves only the metapackages to be the culprit. You have packages in like e.g.
https://pkgbuild.com/~maximbaz/repo/x86_64/maximbaz-base-3.0.0-1-any.pkg.tar.zst.
Is this the metapackage(s) that the script is looking for?

**Comment by maximbaz** [comment]
Precisely... This change adds to pacman config the knowledge of where to look for my metapackages:

https://github.com/maximbaz/dotfiles/blob/7fb76f077744af791004c363a24be22571a2823a/install.sh#L178-L179

And then pacstrap should be able to find the two packages...

Sorry for this, I will fix this once I get a chance to test this properly 😐

**Comment by mortenivar** [comment]
I actually did make the same change also in this line and yet it failed. So I am not sure it will make any change for now. If you test your script thoroughly on a new disk and find that it is working, please let me know by dropping a comment here. For now, I think I'll wait. ;)

**Comment by mokhtarabadi** [comment]
Any news? I encountered this problem...

**Comment by mortenivar** [comment]
Hi Maxim, I noticed that you'd made some changes to the install script and I tried it again. This time it fails because three packages

     hyprland-autorename-workspaces.git
     wluma
     light

are missing from your pkgbuild.com repo. The script depends on them, so it stops because they are not there.

**Comment by 1m-N00b** [comment]
If you want to try it ASAP, you just refer to the [PKGBUILDs](https://github.com/maximbaz/dotfiles/blob/master/packages/PKGBUILD) and install them one by one yourself with comment out `pacstrap -i /mnt maximbaz-base maximbaz-$(uname -m)`?

But It can't manage as a meta-package and it's a hassle to install aur packages such as hyprland-autoname-workspaces-git.

**Comment by maximbaz** [comment]
Hello! 

I think the most responsible course of action for me is to declare that the `install.sh` is no longer meant to be executed directly by anyone, its purpose will now only be to serve as a reference for the "desired state" of the system after installation that I'm personally running.

I'll therefore remove the references from this repo, that it contains an "installation script".

This decision is based on the following factors:

1. I wasn't able to get it fixed since 2022, when this issue got opened (and it was likely broken even before then).
2. I run it too infrequently to be able to catch issues on time (and in fact I haven't run it for years now).
3. Life doesn't let me just run the same Arch Linux, in the past years I had to bootstrap a new system for myself 3 times, and they were macOS, Arch Linux ARM and most recently Fedora (as evident by the growing number of branches in this repo... I haven't decided yet how to deal with this...).
4. Arch Linux now has an official installer!

Just to be clear: anything related to the installation - issues, comments, questions, suggestions, pull requests, etc - are always welcome, I only retract the promise that the installation script can be executed directly.

Hope that's okay with you!

**Comment by mortenivar** [comment]
That is fine. I already use Arch, so it is not that I need your script as such. I just thought it looked kinda cool so I wanted try it on a spare computer I have. I can just use some of the ideas in your script during the installation process with the official installer. As for the previous comment from @1m-N00b, I don't see how this is doable: The PKGBUILD file is fetched remotely by the script and then imported into a database file which is not editable. Therefore, the user is still stuck with the same dependency problem. I just mention this if somebody else might want to try out that suggestion.

**Comment by maximbaz** [comment]
I think what they meant is to replace the line `pacstrap -i /mnt maximbaz-base maximbaz-$(uname -m)` with the line `pacstrap -i /mnt base base-devel dash ...`, where the specific list can be found in the PKGBUILD file. 

To make it even easier, for tinkering purposes I think I'd simply go with the [minimal setup as per Arch wiki](https://wiki.archlinux.org/title/installation_guide#Install_essential_packages) `pacstrap -i /mnt base linux linux-firmware`, and then install additional stuff later on as needed.

**Comment by 1m-N00b** [comment]
yes that's right.Thank you for understanding and translate the meaning from my poor English.

Alternatively, you can create your own aur repo and replace it with your own meta-package. For example, his [install.sh](https://github.com/cyrinux/dotfiles/blob/main/install.sh)

> To make it even easier, for tinkering purposes I think I'd simply go with the [minimal setup as per Arch wiki](https://wiki.archlinux.org/title/installation_guide#Install_essential_packages) `pacstrap -i /mnt base linux linux-firmware`, and then install additional stuff later on as needed.

By the way, this is how I installed it in 2020.

**Comment by mortenivar** [comment]
I managed to get the script to complete the installation by creating a raw text file with all the package names from the PKGBUILD file removing the three packages (wluma, light and hyprland-autorename-workspaces) that caused the problem and then just pass the contents of that file as an argument to pacstrap in the script. Now, I have another problem: How do I become root on this system? No root password was set during installation and the usual method by booting a rescue system and chrooting to '/' to set the password doesn't work.

**Comment by maximbaz** [comment]
The user is being added to `wheel` group, which has `sudo` access, so you can simply use `sudo` to perform privileged operations. Or `sudo su` will give you the root shell.

**Comment by mortenivar** [comment]
I already tried that but it didn't work because the relevant line in the sudoers files was not commented out. I did the whole nine yards with cryptosetup, decrypting, mounting, chrooting etc. and now I can use sudo. I also had another problem: the iwctl station wlan0 connect ... command does not create a connection like in the Arch installation. I had to pacstrap dhclient/dhcpcd also. Everything works now. Thank you, Maxim!

**Comment by maximbaz** [comment]
Great! Enjoy the exploration :grin: 

With https://github.com/maximbaz/dotfiles/commit/082415da6ff44f2a6c4d380a7233e4389f1151ee, I think I'll close the issue, but as said earlier do not hesitate to continue in this thread or opening a new one :wink:

**Comment by mortenivar** [comment]
Thanks ;-). I think you should just remove the three aforementioned packages as dependencies. Make sure that the sudoers file is okay and also include either dhcpcd or dhclient in the list of packages to be installed. Then I think your script would work out of the box for most people.
