### ISSUE TITLE
Suggestion: If your script file doesn't work , then do not LET other people using it!!!

### ISSUE THREAD

**Issue by yizreel-Chen** [maximbaz/dotfiles#51]
I just run your script file and found some of bugs there, so I  decide do drop it, but when I want to open mt tweaks, I found it is broken, beacuse your script file changes some of my file config, but I have no ideal where do you change, So I have to use "grep" command to find all of the places you modified in my whole home directory, then I found you changed lots of my files, including vim, tweaks config files ....

So I recommand if you want other people to use your theme, please write a thorough installtion READ.ME, and if you just wanna use for your self, please let other prople know the potential risk after using your scripts !!!

**Comment by maximbaz** [comment]
Thanks for the suggestion. This is not a theme repo, this is a repo with personal configs, as indicated by the repo name. It's always a good idea to read scripts before running them, things could have been much worse, imagine if the script you found on internet contained `rm -rf /`... In any case, it sounds like you managed to recover, I'm glad to hear it. If you were looking for a config for a particular app, just explore the repo, find the relevant config file and compare it with yours!
