### ISSUE TITLE
Automatically backup the list of installed packages (pacman and AUR).

### ISSUE THREAD

**Issue by webcaptcha** [maximbaz/dotfiles#52]
I find these approach useful but can't figure out how it works. If you don't mind can you point me out to the code where it is realized. Appreciate.

```
 Automatically backup the list of installed packages (pacman and AUR).
These files are used to bootstrap the new system, all apps are installed in one command.
```

**Comment by maximbaz** [comment]
Sure! 

> These files are used to bootstrap the new system, all apps are installed in one command.

I keep the list of packages I have installed in [packages/PKGBUILD](https://github.com/maximbaz/dotfiles/blob/master/packages/PKGBUILD), they are defined as dependencies of my own meta-package. This meta-package (currently experimenting with having a few of those, as you will see), as well as all AUR packages I build locally, are getting [periodically uploaded](https://github.com/maximbaz/dotfiles/blob/master/etc/systemd/system/backup-repo%40.timer) to a public hosting. And so on a fresh system, I [install my meta-package](https://github.com/maximbaz/dotfiles/blob/9f47e3e00a908046f06370bc707aae975af81f1e/install.sh#L187-L188) directly from that hosting, and all the apps get pulled as dependencies. 

> Automatically backup the list of installed packages (pacman and AUR).

When I want to install a new package, I don't modify `packages/PKGBUILD` every time, I simply install it with pacman. There's [a systemd timer](https://github.com/maximbaz/dotfiles/blob/master/.config/systemd/user/backup-packages.timer) that periodically [dumps the diff](https://github.com/maximbaz/dotfiles/blob/master/.local/bin/backup-packages) between `packages/PKGBUILD` and my actual system in `packages/*.list`. I review those from time to time and add what I want to `packages/PKGBUILD`.

I realize this can be confusing and the process consists of many steps. Feel free to ask if you want details on any of the particular pieces of this puzzle, or if you have any other questions 👍

**Comment by maximbaz** [comment]
I hope that answers the question, don't hesitate to reach out again :)
