### ISSUE TITLE
hyprland-autoname-workspaces

### ISSUE THREAD

**Issue by T2hhbmEK** [maximbaz/dotfiles#53]
hyprland-autoname-workspaces-git pkg missing and config untracked.

**Comment by maximbaz** [comment]
Indeed :slightly_smiling_face: I still have a few things related to hyprland in wip and thus untracked, but autoname-workspaces one is pretty easy, pushed now: https://github.com/maximbaz/dotfiles/commit/1ed7b4c664baf2b22fe65144464bad7cd9540e99


The package is on AUR. Let me know if you miss something, and I can help out :wink:
