### ISSUE TITLE
aerc config

### ISSUE THREAD

**Issue by kratnor** [maximbaz/dotfiles#58]
I saw that you deleted your mutt config, will you add the aerc config to git?

**Comment by maximbaz** [comment]
Ideally yes, I'd like to keep certain parts private, and abandoned that when I got stuck splitting it out nicely. But now that you opened the issue, I made a fresh start :grin: It's not everything yet, but a good portion already.

https://github.com/maximbaz/dotfiles/commit/9ba8b68e94da40ae2bf0ef9b7e422f8c610e48ac

What's missing is the actual accounts setup, and `services.mbsync.postExec = "${lib.getExe indexmail}";` which does some notmuch tagging.

Also, even though I have notmuch enabled, I didn't end up actually adding it into aerc yet, I've been trying some things and [this approach](https://bence.ferdinandy.com/2023/07/20/email-in-the-terminal-a-complete-guide-to-the-unix-way-of-email/#unifying-notmuch-account) seems the most promising for me, though a bit quirky as well. I'm still looking if there are better ways!

**Comment by maximbaz** [comment]
With https://github.com/maximbaz/dotfiles/commit/3c5f7d169efb93e7b189262634e13d30f0c45dc9 everything except the actual accounts list is moved to public dotfiles :raised_hands:

**Comment by maximbaz** [comment]
Just if you guys are following and also testing aerc, I did end up trying that notmuch with aerc approach linked above, and it seems to work reasonably well (so I have real accounts as aerc tabs, + notmuch as an additional fake account that is used for search and reply).

https://github.com/maximbaz/dotfiles/commit/99361e9879cd95a247a3f9c0f7d53c8445f24335

together with previously committed

```ini
[messages]
\ = :change-tab notmuch<Enter>:cf<Space>
```

This requires that your aerc account names match the folder names in ~/.mail
