### ISSUE TITLE
What is the font used in the terminal ?

### ISSUE THREAD

**Issue by ApolloBian** [maximbaz/dotfiles#8]
It looks really nice
![image](https://user-images.githubusercontent.com/13659369/44169984-8f40d080-a108-11e8-8526-f072fdcc9908.png)

**Comment by maximbaz** [comment]
@ApolloBian that one is Consolas. Currently I use [Fira Code](https://github.com/tonsky/FiraCode), it's also  quite good, comes with powerline symbols and has font ligatures — definitely check it out.

**Comment by ApolloBian** [comment]
@maximbaz thanks

**Comment by maximbaz** [comment]
Here's a picture of neofetch with Fira Code, for comparison:

![image](https://user-images.githubusercontent.com/1177900/44170333-52a8b100-a0d7-11e8-9d0c-97902d8bb4b8.png)

**Comment by dmxt** [comment]
@maximbaz You should check out a new font family [JetBrains](https://www.jetbrains.com/lp/mono/) :)

![Screenshot_20200229_090130](https://user-images.githubusercontent.com/3248782/75608955-45dd8980-5ad2-11ea-891b-8bab52a80cfc.png)

There's a nerd patched version on AUR and it already got ligatures on default. Tbh I don't think I've ever seen more ligature than this.

![Screenshot_20200229_090443](https://user-images.githubusercontent.com/3248782/75608975-8b9a5200-5ad2-11ea-90d0-89c50d8c7b76.png)

---

Anyway, your dotfiles are awesome! I hope I'll be able to learn how to build something like you did. It's super organized and neat and I still have no idea what is the proper way to organize files.

**Comment by maximbaz** [comment]
Thanks for sharing @dmxt! I actually stopped using fonts with ligatures, right now I'm simply using Input font with the following configuration:

http://input.fontbureau.com/download/?customize&fontSelection=fourStyleFamily&regular=InputMonoNarrow-Regular&italic=InputMonoNarrow-Italic&bold=InputMonoNarrow-Bold&boldItalic=InputMonoNarrow-BoldItalic&a=0&g=0&i=serifs_round&l=serifs_round&zero=slash&asterisk=height&braces=0&preset=default&line-height=1.1&email=

JetBrains font looks quite neat, also condensed, I like 👍 

Enjoy the dotfiles, and feel free to ping me or create new issues if you have any questions.
